services:
  - type: web
    name: fb-profile-downloader
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
    autoDeploy: true
    plan: free
    region: oregon # You can change this to your preferred region
    healthCheckPath: /
    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - render.yaml
        - build.sh
        - start.sh
