services:
  - type: web
    name: facebook-browser-lite
    runtime: python
    plan: free  # Using free tier for lightweight deployment
    buildCommand: |
      # Install Python dependencies first
      pip install -r requirements.txt
      
      # Update and install system dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        curl \
        ca-certificates \
        --no-install-recommends
      
      # Install Chromium (more reliable than Chrome on Render.com)
      echo "Installing Chromium..."
      apt-get install -y chromium-browser --no-install-recommends
      
      # Verify installation
      if [ -f "/usr/bin/chromium-browser" ]; then
        echo "✅ Chromium installed successfully"
        /usr/bin/chromium-browser --version
      else
        echo "❌ Chromium installation failed"
        exit 1
      fi
      
      # Install ChromeDriver compatible with Chromium
      echo "Installing ChromeDriver..."
      CHROMIUM_VERSION=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+')
      CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROMIUM_VERSION%%.*}")
      
      if [ -n "$CHROMEDRIVER_VERSION" ]; then
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip" -O /tmp/chromedriver.zip
        unzip -q /tmp/chromedriver.zip -d /tmp/
        mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
        chmod +x /usr/bin/chromedriver
        echo "✅ ChromeDriver installed successfully"
        /usr/bin/chromedriver --version
      else
        echo "❌ Could not determine ChromeDriver version, installing fallback"
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.86/linux64/chromedriver-linux64.zip" -O /tmp/chromedriver.zip
        unzip -q /tmp/chromedriver.zip -d /tmp/
        mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
        chmod +x /usr/bin/chromedriver
      fi
      
      # Clean up
      apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*
      
      echo "Build completed successfully!"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WDM_LOCAL
        value: "1"
      - key: CHROME_BIN
        value: "/usr/bin/chromium-browser"
      - key: CHROMEDRIVER_PATH
        value: "/usr/bin/chromedriver"
    healthCheckPath: /health
    autoDeploy: true
