services:
  - type: web
    name: fb-profile-downloader
    runtime: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "export PATH=\"${PATH}:/opt/render/project/.render/chrome/opt/google/chrome\"; gunicorn app:app --timeout 120 --workers 1 --threads 1 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: 1
      - key: CHROME_BIN
        value: /opt/render/project/.render/chrome/opt/google/chrome/chrome
    autoDeploy: true
    plan: free
    region: oregon # You can change this to your preferred region
    healthCheckPath: /health
    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - render.yaml
        - build.sh
