services:
  - type: web
    name: fb-profile-picture-api
    env: node
    plan: free
    rootDir: api
    buildCommand: "npm install && npx puppeteer browsers install chrome"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
    healthCheckPath: /health
    autoDeploy: true