services:
  - type: web
    name: facebook-browser-lite
    runtime: python
    plan: free  # Using free tier for lightweight deployment
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Update system and install dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        curl \
        ca-certificates \
        --no-install-recommends
      
      # Install Chromium (most compatible with Render.com)
      echo "Installing Chromium..."
      apt-get install -y chromium-browser --no-install-recommends
      
      # Verify Chromium installation
      if [ -x "/usr/bin/chromium-browser" ]; then
        echo "✅ Chromium installed and executable"
        CHROME_VERSION=$(/usr/bin/chromium-browser --version)
        echo "Chromium version: $CHROME_VERSION"
      else
        echo "❌ Chromium not found or not executable"
        echo "Checking installed packages..."
        dpkg -l | grep chromium || echo "No chromium packages found"
        exit 1
      fi
      
      # Install ChromeDriver
      echo "Installing ChromeDriver..."
      CHROMIUM_VERSION=$(chromium-browser --version | grep -oP '\d+\.\d+\.\d+')
      MAJOR_VERSION=${CHROMIUM_VERSION%%.*}
      CHROMEDRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/${MAJOR_VERSION}.0.6613.86/linux64/chromedriver-linux64.zip"
      
      wget -q "$CHROMEDRIVER_URL" -O /tmp/chromedriver.zip || {
        echo "Primary ChromeDriver URL failed, trying fallback..."
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.86/linux64/chromedriver-linux64.zip" -O /tmp/chromedriver.zip
      }
      
      unzip -q /tmp/chromedriver.zip -d /tmp/
      mv /tmp/chromedriver-linux64/chromedriver /usr/bin/chromedriver
      chmod +x /usr/bin/chromedriver
      
      if [ -x "/usr/bin/chromedriver" ]; then
        echo "✅ ChromeDriver installed and executable"
        /usr/bin/chromedriver --version
      else
        echo "❌ ChromeDriver installation failed"
        exit 1
      fi
      
      # Clean up
      apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*
      
      echo "Build completed successfully!"
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WDM_LOCAL
        value: "1"
      - key: CHROME_BIN
        value: "/usr/bin/chromium-browser"
      - key: CHROMEDRIVER_PATH
        value: "/usr/bin/chromedriver"
      - key: DEBUG
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
