services:
  - type: web
    name: fb-profile-picture-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production