services:
  - type: web
    name: fb-profile-downloader
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: 1
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
      - key: DEBUG
        value: "true"
    autoDeploy: true
    plan: free
    region: oregon
    healthCheckPath: /health
